2025-01-02 16:35:28,525 - src.batch_etl.load.datalake_loader - ERROR - Error initializing zones: java.net.UnknownHostException: namenode
2025-01-02 16:35:28,529 - py4j.clientserver - INFO - Closing down clientserver connection
